### ISSUE TITLE
Make times sticky

### ISSUE THREAD

**Issue by reuterm** [superosku/laguuni-fixer#2]
Right now it can be difficult to keep track what time a slot belongs to.
Example:
![Screenshot 2021-05-10 at 18 18 33](https://user-images.githubusercontent.com/14981901/117682894-353b9f80-b1bc-11eb-9b70-bf23dfeb97e7.png)

This could be improved by making the time column stick to the left.

**Comment by superosku** [comment]
Thanks for the suggestion. It is implemented.
